#include "freertos/FreeRTOS.h"

#ifndef BUZZER_BEEP_TYPE_H
#define BUZZER_BEEP_TYPE_H

typedef enum
{
    RESPAWN_NO_TOKENS,
    RESPAWN_TOKEN_DECREMENT,
    RESPAWN_BATCH,
    SETUP_MODE_ENABLED,
    SETUP_MODE_DISABLED,
} BUZZER_BEEP_TYPE;

#endif